### ISSUE TITLE
Handle HTTPErrors properly in ConnectionManager

### ISSUE THREAD

**Issue by pajlada** [pajlada/pajbot#109]
This exception occured earlier

```python
Traceback (most recent call last):
  File "./main.py", line 64, in <module>
    run(args)
  File "./main.py", line 47, in run
    pajbot.start()
  File "/home/pajlada/git/pajbot/pajbot/bot.py", line 409, in start
    self.reactor.process_forever()
  File "/home/pajlada/.local/lib64/python3.4/site-packages/irc/client.py", line 278, i
n process_forever
    self.process_once(timeout)
  File "/home/pajlada/.local/lib64/python3.4/site-packages/irc/client.py", line 262, i
n process_once
    self.process_timeout()
  File "/home/pajlada/.local/lib64/python3.4/site-packages/irc/client.py", line 228, i
n process_timeout
    command.function()
  File "/home/pajlada/git/pajbot/pajbot/models/connection.py", line 118, in run_mainte
nance
    newconn = self.make_new_connection()
  File "/home/pajlada/git/pajbot/pajbot/models/connection.py", line 141, in make_new_c
onnection
    data = self.bot.twitchapi.get(['channels', self.streamer, 'chat_properties'])
  File "/home/pajlada/git/pajbot/pajbot/apiwrappers.py", line 60, in get
    data = self.getraw(endpoints, parameters, base=base)
  File "/home/pajlada/git/pajbot/pajbot/apiwrappers.py", line 57, in getraw
    return self._get(self.get_url(endpoints, parameters, base=base), self.headers)
  File "/home/pajlada/git/pajbot/pajbot/apiwrappers.py", line 24, in _get
    raise e
  File "/home/pajlada/git/pajbot/pajbot/apiwrappers.py", line 20, in _get
    response = urllib.request.urlopen(req, timeout=30)
  File "/usr/lib64/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.4/urllib/request.py", line 469, in open
    response = meth(req, response)
  File "/usr/lib64/python3.4/urllib/request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.4/urllib/request.py", line 507, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.4/urllib/request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
```

**Comment by pajlada** [comment]
fixed
