### ISSUE TITLE
PajBot website

### ISSUE THREAD

**Issue by alphuite** [pajlada/pajbot#314]
I can't run the pajbot webiste, it gives me following error:

`Traceback (most recent call last):`
  `File "/srv/pajbot/pajbot/web/common/tasks.py", line 11, in init`
    `from uwsgidecorators import thread, timer`
  `File "/srv/pajbot/myvenv/lib/python3.4/site-packages/uwsgidecorators.py", line 10, in <module>`
    `import uwsgi`
`ImportError: No module named 'uwsgi'`

**Comment by alphuite** [comment]
I reinstalled uwsgi
fixed
